const RoleRouter = require("./roleRoute");
const RolePermissionRouter = require("./rolesPermissionRoute");
const BranchRouter = require("./branchRoute");
const BankAccountRouter = require("./bankAccountRoute");
const KycDocumentRouter = require("./kycDocumentRoute");
const MaterialTypeRoute = require("./materialTypeRoute");
const CategoryRouter = require("./categoryRoute");
const SubcategoryRouter = require("./subcategoryRoute");
const VariantRouter = require("./variantRoute");
const ImageUploadRoute = require("./imageUploadRoute");
const UserLoginService = require("./userLoginRoute");
const VendorSpocDetailsRoute = require("./vendorSpocDetailsRoute");
const VendorRoutes = require("./vendorRoute");
const ProductRouter = require('./productRoute');
const GrnRouter = require('./grnRoute');

module.exports = (app) => {
  app.use("/api/v1", RoleRouter);
  app.use("/api/v1", RolePermissionRouter);
  app.use("/api/v1", BranchRouter);
  app.use("/api/v1", BankAccountRouter);
  app.use("/api/v1", KycDocumentRouter);
  app.use("/api/v1", MaterialTypeRoute);
  app.use("/api/v1", CategoryRouter);
  app.use("/api/v1", SubcategoryRouter);
  app.use("/api/v1", ImageUploadRoute);
  app.use("/api/v1", UserLoginService);
  app.use("/api/v1", VendorSpocDetailsRoute);
  app.use("/api/v1", VendorRoutes);
  app.use("/api/v1", ProductRouter);
  app.use("/api/v1", GrnRouter);
};
